apiVersion: v1
kind: Secret
metadata:
  name: gitlab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://192.168.56.110/root/ytaya42-inception.git
  insecure: "true"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
spec:
  sourceRepos:
    -  https://192.168.56.110/root/ytaya42-inception.git
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-app-v1
  namespace: argocd
spec:
  project: development
  source:
    repoURL: https://192.168.56.110/root/ytaya42-inception.git
    targetRevision: main
    path: v1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
