Vagrant.configure("2") do |config|
  nodes = {
    "Gitlab"  => { ip: "192.168.56.110", script: "Provision/controller.sh" },
  }

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  nodes.each do |name, opts|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: opts[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 4
        vb.gui = false
      end

      node.vm.provision "shell", path: opts[:script]
    end
  end
end

